theme: jekyll-theme-slate
Title: Welcome to my pages
Description: about my 3 months life in Evanston. I am new to this town and also this country.  Record what I found, I saw and I learned during this period.
